/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.sql.*;
import helper.Koneksi;
import javax.swing.*;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import model.Menu;

/**
 *
 * @author acer
 */
public class DashboardViews extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public DashboardViews() {
        initComponents();
        setLocationRelativeTo(null);
        
        new controller.DashboardController(this);
        
        TableColumn idColumn = jTable_Menu.getColumnModel().getColumn(0); // Kolom ID
        idColumn.setMinWidth(0);
        idColumn.setMaxWidth(0);
        idColumn.setPreferredWidth(0);


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jText_Cari = new javax.swing.JTextField();
        Cari = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Menu = new javax.swing.JTable();
        Mulai_Pesan = new javax.swing.JButton();
        jButton_TampilkanMenu = new javax.swing.JButton();
        LogOut = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Aplikasi Pemesanan Di Kantin");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 280, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Cari Menu");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 80, -1));

        jText_Cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_CariActionPerformed(evt);
            }
        });
        getContentPane().add(jText_Cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 530, -1));

        Cari.setBackground(new java.awt.Color(51, 153, 255));
        Cari.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Cari.setForeground(new java.awt.Color(255, 255, 255));
        Cari.setText("Cari");
        Cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CariActionPerformed(evt);
            }
        });
        getContentPane().add(Cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 70, 100, -1));

        jTable_Menu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable_Menu);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 740, 237));

        Mulai_Pesan.setBackground(new java.awt.Color(0, 204, 102));
        Mulai_Pesan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Mulai_Pesan.setForeground(new java.awt.Color(255, 255, 255));
        Mulai_Pesan.setText("Pesan");
        Mulai_Pesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mulai_PesanActionPerformed(evt);
            }
        });
        getContentPane().add(Mulai_Pesan, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 400, 240, -1));

        jButton_TampilkanMenu.setBackground(new java.awt.Color(153, 153, 255));
        jButton_TampilkanMenu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton_TampilkanMenu.setForeground(new java.awt.Color(255, 255, 255));
        jButton_TampilkanMenu.setText("Tampilkan Menu");
        getContentPane().add(jButton_TampilkanMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 230, -1));

        LogOut.setBackground(new java.awt.Color(153, 0, 51));
        LogOut.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LogOut.setForeground(new java.awt.Color(255, 255, 255));
        LogOut.setText("Log Out");
        LogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutActionPerformed(evt);
            }
        });
        getContentPane().add(LogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 10, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\acer\\Downloads\\bg.jpg")); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-290, -100, 1180, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jText_CariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_CariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_CariActionPerformed

    private void CariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CariActionPerformed

    private void Mulai_PesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mulai_PesanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Mulai_PesanActionPerformed

    private void LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutActionPerformed
        int pilihan = JOptionPane.showConfirmDialog(
            this, 
            "Apakah kamu yakin ingin keluar?", 
            "Konfirmasi Logout", 
            JOptionPane.YES_NO_OPTION, 
            JOptionPane.QUESTION_MESSAGE
        );

        if (pilihan == JOptionPane.YES_OPTION) {
            this.dispose();
            System.exit(0);
        }
    }//GEN-LAST:event_LogOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardViews.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardViews.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardViews.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardViews.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardViews().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cari;
    private javax.swing.JButton LogOut;
    private javax.swing.JButton Mulai_Pesan;
    private javax.swing.JButton jButton_TampilkanMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Menu;
    private javax.swing.JTextField jText_Cari;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnCari() {
        return Cari;
    }

    public JButton getBtnPesan() {
        return Mulai_Pesan;
    }

    public String getTxtCari() {
        return jText_Cari.getText();
    }

    public JButton getjButton_TampilkanMenu() {
        return jButton_TampilkanMenu;
    }

    public JTable getTableMenu() {
        return jTable_Menu;
    }
    
    public void setTableMenuModel(DefaultTableModel model) {
        jTable_Menu.setModel(model);
    }
    
    public void clearSearchBar() {
        jText_Cari.setText("");
    }

    @Override
    public void dispose() {
        super.dispose();
    }
}
