/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.sql.SQLException;
import controller.PesananController;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import view.DashboardViews;

/**
 *
 * @author acer
 */
public class PesananViews extends javax.swing.JFrame {

    /**
     * Creates new form Pesanan
     */
    private controller.PesananController controller;

    
    public PesananViews() {
        initComponents();
        controller = new PesananController(this);
        setLocationRelativeTo(null);
        
        DefaultTableModel model = new DefaultTableModel(
        new String[] {"ID", "Nama Menu", "Jumlah", "Harga", "Total Harga"}, 0);
        jTable_Pesanan.setModel(model);
        
        
        TableColumn idColumn = jTable_Pesanan.getColumnModel().getColumn(0); // id_menu
        idColumn.setMinWidth(0);
        idColumn.setMaxWidth(0);
        idColumn.setPreferredWidth(0);

        TableColumn hargaColumn = jTable_Pesanan.getColumnModel().getColumn(3); // harga
        hargaColumn.setMinWidth(0);
        hargaColumn.setMaxWidth(0);
        hargaColumn.setPreferredWidth(0);
        
        jTable_Pesanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int row = jTable_Pesanan.getSelectedRow();
                if (row >= 0) {
                    String makanan = jTable_Pesanan.getValueAt(row, 1).toString();
                    String jumlah = jTable_Pesanan.getValueAt(row, 2).toString();

                    jText_Makanan.setText(makanan);
                    jText_Jumlah.setText(jumlah);
                }
            }
        });
        
        Pesan.addActionListener(new ActionListener() {
        public void actionPerformed(ActionEvent e) {
            DashboardViews dashboard = new DashboardViews();
            dashboard.setVisible(true);
            dashboard.setLocationRelativeTo(null);
            dispose();
        }
    });
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jText_Makanan = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jText_Jumlah = new javax.swing.JTextField();
        TambahPesanan = new javax.swing.JButton();
        DeletePesanan = new javax.swing.JButton();
        Pesan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Pesanan = new javax.swing.JTable();
        EditPesanan = new javax.swing.JButton();
        ClearPesanan = new javax.swing.JButton();
        LogOut = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Aplikasi Pemesanan Di Kantin");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 280, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Pesanan");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        jText_Makanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_MakananActionPerformed(evt);
            }
        });
        getContentPane().add(jText_Makanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 289, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Jumlah Pesanan");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        jText_Jumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_JumlahActionPerformed(evt);
            }
        });
        getContentPane().add(jText_Jumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 289, -1));

        TambahPesanan.setBackground(new java.awt.Color(51, 153, 255));
        TambahPesanan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TambahPesanan.setForeground(new java.awt.Color(255, 255, 255));
        TambahPesanan.setText("Tambah Pesanan");
        TambahPesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahPesananActionPerformed(evt);
            }
        });
        getContentPane().add(TambahPesanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 200, -1));

        DeletePesanan.setBackground(new java.awt.Color(255, 0, 0));
        DeletePesanan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        DeletePesanan.setForeground(new java.awt.Color(255, 255, 255));
        DeletePesanan.setText("Delete Pesanan");
        DeletePesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletePesananActionPerformed(evt);
            }
        });
        getContentPane().add(DeletePesanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 200, -1));

        Pesan.setBackground(new java.awt.Color(0, 204, 102));
        Pesan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Pesan.setForeground(new java.awt.Color(255, 255, 255));
        Pesan.setText("Pesan");
        Pesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesanActionPerformed(evt);
            }
        });
        getContentPane().add(Pesan, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 200, -1));

        jTable_Pesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable_Pesanan);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, 428, 290));

        EditPesanan.setBackground(new java.awt.Color(204, 102, 255));
        EditPesanan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        EditPesanan.setForeground(new java.awt.Color(255, 255, 255));
        EditPesanan.setText("Edit Pesananan");
        EditPesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditPesananActionPerformed(evt);
            }
        });
        getContentPane().add(EditPesanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 200, -1));

        ClearPesanan.setBackground(new java.awt.Color(255, 102, 204));
        ClearPesanan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ClearPesanan.setForeground(new java.awt.Color(255, 255, 255));
        ClearPesanan.setText("Clear Pesanan");
        ClearPesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearPesananActionPerformed(evt);
            }
        });
        getContentPane().add(ClearPesanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 200, -1));

        LogOut.setBackground(new java.awt.Color(153, 0, 51));
        LogOut.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LogOut.setForeground(new java.awt.Color(255, 255, 255));
        LogOut.setText("Log Out");
        LogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutActionPerformed(evt);
            }
        });
        getContentPane().add(LogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 10, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\acer\\Downloads\\bg.jpg")); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-260, -110, 1220, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jText_MakananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_MakananActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_MakananActionPerformed

    private void jText_JumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_JumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_JumlahActionPerformed

    private void TambahPesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahPesananActionPerformed
        controller.tambahPesanan();
        controller.tampilData();
    }//GEN-LAST:event_TambahPesananActionPerformed

    private void DeletePesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletePesananActionPerformed
        controller.hapusPesanan();
        controller.tampilData();
    }//GEN-LAST:event_DeletePesananActionPerformed

    private void PesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesanActionPerformed
        JOptionPane.showMessageDialog(this, "Pesanan telah dikirim ke dapur! 🍽️");
        controller.clearForm();
        controller.tampilData();
    }//GEN-LAST:event_PesanActionPerformed

    private void EditPesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditPesananActionPerformed
        controller.clearForm();
        controller.updatePesanan();
        controller.tampilData();
    }//GEN-LAST:event_EditPesananActionPerformed

    private void ClearPesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearPesananActionPerformed
        controller.clearPesanan();
        controller.tampilData();
    }//GEN-LAST:event_ClearPesananActionPerformed

    private void LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutActionPerformed
        int pilihan = JOptionPane.showConfirmDialog(
            this, 
            "Apakah kamu yakin ingin keluar?", 
            "Konfirmasi Logout", 
            JOptionPane.YES_NO_OPTION, 
            JOptionPane.QUESTION_MESSAGE
        );

        if (pilihan == JOptionPane.YES_OPTION) {
            this.dispose();
            System.exit(0);
        }
    }//GEN-LAST:event_LogOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PesananViews.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PesananViews.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PesananViews.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PesananViews.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PesananViews().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ClearPesanan;
    private javax.swing.JButton DeletePesanan;
    private javax.swing.JButton EditPesanan;
    private javax.swing.JButton LogOut;
    private javax.swing.JButton Pesan;
    private javax.swing.JButton TambahPesanan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Pesanan;
    private javax.swing.JTextField jText_Jumlah;
    private javax.swing.JTextField jText_Makanan;
    // End of variables declaration//GEN-END:variables

    public JButton getDeletePesanan() {
        return DeletePesanan;
    }

    public void setDeletePesanan(JButton DeletePesanan) {
        this.DeletePesanan = DeletePesanan;
    }

    public JButton getPesan() {
        return Pesan;
    }

    public void setPesan(JButton Pesan) {
        this.Pesan = Pesan;
    }

    public JButton getTambahPesanan() {
        return TambahPesanan;
    }

    public void setTambahPesanan(JButton TambahPesanan) {
        this.TambahPesanan = TambahPesanan;
    }

    public JButton getClearPesanan() {
        return ClearPesanan;
    }

    public void setClearPesanan(JButton ClearPesanan) {
        this.ClearPesanan = ClearPesanan;
    }

    public JButton getEditPesanan() {
        return EditPesanan;
    }

    public void setEditPesanan(JButton EditPesanan) {
        this.EditPesanan = EditPesanan;
    }
    
    public JTable getjTable_Pesanan() {
        return jTable_Pesanan;
    }

    public void setjTable_Pesanan(JTable jTable_Pesanan) {
        this.jTable_Pesanan = jTable_Pesanan;
    }

    public JTextField getjText_Makanan() {
        return jText_Makanan;
    }

    public void setjText_Makanan(JTextField jText_Makanan) {
        this.jText_Makanan = jText_Makanan;
    }

    public JTextField getjText_Jumlah() {
        return jText_Jumlah;
    }

    public void setjText_Jumlah(JTextField jText_Jumlah) {
        this.jText_Jumlah = jText_Jumlah;
    }

    public JTable getTablePesanan() {
        return jTable_Pesanan;
    }


}
